name: PR
on: push

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'test', 'build']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn --version

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - run: yarn --version

      - name: ${{ matrix.step }}
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn ${{ matrix.step }}
